### ISSUE TITLE
nextcloud    | tar: <path> Cannot change ownership to uid 65534, gid 65533: Operation not permitted

### ISSUE THREAD

**Issue by raupie** [linuxserver/docker-nextcloud#107]
I'm running a FreeNAS | Rancher VM setup. I have created several NFS shares and have them mounted on the Rancher Host VM and now trying to use the linuxserver | nextcloud docker container in a docker-compose setup. 

My `docker-compose.yml` file.

```
version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - mariadb
    links:
      - mariadb
    environment:
      - TZ=America/New_York 
      - PUID=10001
      - PGID=10001
    ports:
      - 8443:443
    volumes:
      - /mnt/cloud/config:/config
      - /mnt/cloud/data:/data
  mariadb:
    image: linuxserver/mariadb
    container_name: nextcloud-mariadb
    restart: unless-stopped
    environment:
      - PUID=1100
      - PGID=1100
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
    volumes:
      - /mnt/docker/nextcloud/mariadb:/config
    ports:
      - 3308:3306
```
As you can see I'm mounting from the host rancher vm's nfs folders. When I run a `docker-compose up` and I check the logs `docker-compose logs -f` I can see a endless loop of this error message when the nextcloud tar is being extracted. 

`nextcloud    | tar: <path> Cannot change ownership to uid 65534, gid 65533: Operation not permitted`

I suppose this has to do with the root user in the nextcloud container extracting and my nfs setup is using `no_squash`.

Is there any NFS tips for the community on how to get this container to work with NFS shares as volume bind mounts? Perhaps untar locally first and then share the folder? 

`FreeNAS dataset -> RancherVM Host NFS Mount -> Nextcloud container bind volume mount.`

Thanks for your time and another excellent docker container :)
