### ISSUE TITLE
Allfontsgen not found when installing community document server

### ISSUE THREAD

**Issue by hughesjs** [linuxserver/docker-nextcloud#154]
I'm installing the Community Document Server, following along with this article: https://nextcloud.com/blog/how-to-install-onlyoffice-in-nextcloud-hub-and-new-integration-feature/. It should be noted that this is on a fresh install.

After executing `occ app:install documentserver_community` I get this error:

> Error: sh: ../../tools/allfontsgen: not found

My docker-compose file:

```
version: "3"
networks:
        reverse-proxy:
                external: true
        nc-int:
                external: false
services:
        nextcloud:
                image: linuxserver/nextcloud:latest
                container_name: nextcloud
                environment:
                        - PUID=1010
                        - GUID=1013
                        - TZ=Europe/London
                volumes:
                        - /docker-volumes/nextcloud/config:/config                        
                        - /datapool/data:/data
                networks:
                        - reverse-proxy
                        - nc-int
                depends_on:
                        - db
                restart: unless-stopped
        db:
                image: mysql:5.7.30
                container_name: nc_mysql
                restart: unless-stopped
                environment:
                        - MYSQL_ROOT_PASSWORD=redacted
                        - MYSQL_USER=nextcloud
                        - MYSQL_PASSWORD=redacted
                        - MYSQL_DATABASE=nextcloud
                networks:
                        - nc-int
                volumes:
                        - /docker-volumes/nextcloud/mysql:/var/lib/mysql
```

I have tried deleting the persistent volumes and recreating everything but I get the same problem.
