### ISSUE TITLE
Example to run this with mysql/mariadb?

### ISSUE THREAD

**Issue by needforspeed** [linuxserver/docker-nextcloud#170]
This is not a bug, but I'm wondering if there is any example to use this with mysql.  For example the docker-compose.yml file?
Thanks

**Comment by hugalafutro** [comment]
this is what i'm using:
```
version: "3.7"

services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 9443:443
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: linuxserver/mariadb:latest
    container_name: nextcloud_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
    volumes:
      - ./config_db:/config
    restart: unless-stopped
```
with the variables defined in `.env` file placed along `docker-compose.yml` like so:
```
TIMEZONE=Europe/London
DB_ROOT_PW=rootpw
DB_NAME=nextcloud
DB_USER=dbuser
DB_PW=cloudnext
```
