### ISSUE TITLE
INotify file watcher app couldn't be installed because inotify is not available

### ISSUE THREAD

**Issue by AndreaPro** [linuxserver/docker-nextcloud#197]
## Expected Behavior
Install "INotify file watcher" app from the Web UI

## Current Behavior
When installing it the following error is displayed:
App "INotify file watcher" cannot be installed because the following dependencies are not fulfilled: The library inotify is not available

## Steps to Reproduce
1. Go to Apps section in Nextcloud Web UI
2. Search for INotify file watcher and press Download and Enable
3. Error reported above is displayed

## Environment
**OS:** Debian GNU/Linux 10 (buster) with OpenMediaVault 5.6.3-1
**CPU architecture:** x86_64
**How docker service was installed:**
Installed with default setting in OMV Extras of OpenMediaVault

## Command used to create docker container
```
---
version: "2"
services:
  nextcloud:
#    image: linuxserver/nextcloud:arm64v8-18.0.3-ls76
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Rome
    volumes:
      - /srv/dev-disk-by-label-01/active/apps/nextcloud/config:/config
      - /srv/dev-disk-by-label-01/active/apps/nextcloud/data:/data
      - /srv/dev-disk-by-label-01/active/Shares/:/data/ext_storage/Shares
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
  mariadb:
    image: linuxserver/mariadb
    container_name: nextcloud-mariadb
    environment:
      - PUID=1000
      - PGID=100
      - MYSQL_ROOT_PASSWORD=****
      - MYSQL_DATABASE=****
      - MYSQL_USER=****
      - MYSQL_PASSWORD=****
      - TZ=Europe/London
    volumes:
      - /apps/nextcloud-mariadb:/config
    restart: unless-stopped
  redis:
    image: redis
    container_name: nextcloud-redis
    restart: unless-stopped
networks:
  default:
    external:
      name: swag
```

## Docker logs
No errors displayed

On the app website is stated that php inotify extension is required to run this app.
Is possible to add the php inotify extension to the docker image?
