### ISSUE TITLE
Cron not installed

### ISSUE THREAD

**Issue by tourshi** [linuxserver/docker-nextcloud#230]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Installation should run properly.

## Current Behavior
Nextcloud appears to install (from adding users to starting services). However after the services start, there is an error that prevents Nextcloud from completing. 

This is the error: 

nextcloud     | Exception: Not installed in /config/www/nextcloud/lib/base.php:277
nextcloud     | Stack trace:
nextcloud     | #0 /config/www/nextcloud/lib/base.php(649): OC::checkInstalled()
nextcloud     | #1 /config/www/nextcloud/lib/base.php(1087): OC::init()
nextcloud     | #2 /config/www/nextcloud/cron.php(43): require_once('/config/www/nex...')
nextcloud     | #3 {main}

## Steps to Reproduce
Here is my docker-compose file: 
```

version: '3'
networks:
  web:
    external: true
services:
  nextcloud:
    restart: unless-stopped
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    networks:
        - web
    labels:
        - traefik.http.routers.nextcloud.rule=Host(`cloud.domain.com`)
        - traefik.http.routers.nextcloud.tls=true
        - traefik.http.routers.nextcloud.tls.certresolver=lets-encrypt
        - traefik.http.services.nextcloud.loadbalancer.server.scheme=https
        - traefik.http.services.nextcloud.loadbalancer.server.port=443
        - traefik.port=443
    volumes:
      - ./data:/data
      - ./config:/config
    depends_on:
      - nextcloud_db
  nextcloud_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextcloud_db
    environment:
        - PUID=1000
        - PGID=1000
        - MYSQL_ROOT_PASSWORD=password
        - TZ=America/Toronto
        - MYSQL_DATABASE=nextcloud #optional
        - MYSQL_USER=nextcloud #optional
        - MYSQL_PASSWORD=password
    volumes:
      - /db:/config
    restart: unless-stopped
```
## Environment
**OS: Debian 11**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
latest Docker from official repo

## Command used to create docker container (run/create/compose/screenshot)
docker-compose up

## Docker logs
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
..................................................................................+++++
................................................+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing... 
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-install: executing... 
[cont-init.d] 50-install: exited 0.
[cont-init.d] 60-memcache: executing... 
[cont-init.d] 60-memcache: exited 0.
[cont-init.d] 70-aliases: executing... 
[cont-init.d] 70-aliases: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Exception: Not installed in /config/www/nextcloud/lib/base.php:277
Stack trace:
#0 /config/www/nextcloud/lib/base.php(649): OC::checkInstalled()
#1 /config/www/nextcloud/lib/base.php(1087): OC::init()
#2 /config/www/nextcloud/cron.php(43): require_once('/config/www/nex...')
#3 {main}
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

This appears to be reported earlier in issue #203
