### ISSUE TITLE
Updated to latest container and now getting php module errors

### ISSUE THREAD

**Issue by YouveGotMeowxy** [linuxserver/docker-nextcloud#268]
![image](https://user-images.githubusercontent.com/39491297/197834617-65aa5321-f174-489e-87b7-fca8d4dc7c1d.png)

```
[24-Oct-2022 13:06:01] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl.so' (tried: /usr/lib/php8/modules/openssl.so (Error relocating /usr/lib/php8/modules/openssl.so: zend_argument_error_variadic: symbol not found), /usr/lib/php8/modules/openssl.so.so (Error loading shared library /usr/lib/php8/modules/openssl.so.so: No such file or directory)) in Unknown on line 0
```

Using: `ghcr.io/linuxserver/nextcloud:php8`

```
Using:  nextcloud:
    image: 'ghcr.io/linuxserver/nextcloud:php8'
    hostname: 'nextcloud'
    #runtime: 'crun'
    environment:
      TZ: 'America/Chicago'
      PUID: '1000'
      PGID: '1000'
      DOCKER_MODS: 'linuxserver/mods:nextcloud-mediadc'
    volumes:
      - '/opt/docker/configs/nextcloud/config:/config:rw'                     # Configs
      - '/opt/docker/configs/nextcloud/.bashrc:/root/.bashrc:rw'              # Custom Bash
      - '/mnt/e/Docker/Nextcloud:/data:rw'                                    # Storage
      - '/opt/docker/configs/nextcloud/php.ini:/etc/php7/php.ini:ro'          # Custom php.ini
      - '/opt/docker/configs/nextcloud/logrotate.conf:/etc/logrotate.conf:ro' # Custom Logrotate
      - '/mnt/e/Docker/Logs/nextcloud:/config/log:rw'                         # Logs
      - '/mnt/e/Docker/Logs/nextcloud/nextcloud.log:/data/nextcloud.log:rw'
      - '/mnt/e/Docker/Logs/nextcloud/audit.log:/data/audit.log:rw'
    deploy:
      mode: 'replicated'
      replicas: 1
      placement:
        constraints:
          - 'node.labels.Main == true'
      resources:
        limits:
          # cpus: '1.0'
          memory: '1G'
      restart_policy:
        condition: 'any'
    networks:
      - 'clouds-syncs'
      - 'elk' # Elasticsearch
      - 'mysql'
      - 'redis' # Caching
```
