### ISSUE TITLE
Nextcloud 25 Photo 2.0 Recognition requires libtensorflow

### ISSUE THREAD

**Issue by J4gQBqqR** [linuxserver/docker-nextcloud#276]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Nextcloud 25's new Photo app now officially supports object and facial recognition. However, the container does not seem to provide enough dependencies for it to run efficiently.

## Current Behavior

![图片](https://user-images.githubusercontent.com/77554817/202285041-c1910bec-1a03-44b1-b5ac-640dcc963ff6.png)

## Steps to Reproduce

1. Install Nextcloud 25
2. Enable the Photo app and the Recognition app
3. Go to the Recognition settings in administrator setting panel
4. See the above warnings in the screenshot

## Environment
**OS:** Arch
**CPU architecture:** x86_64
**How docker service was installed:**
from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)

```
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:25.0.1-php8
    container_name: nextcloud
    networks:
      pgsql:
      xxxx:
        ipv4_address: x.x.x.x
    environment:
      - PUID=33
      - PGID=33
      - TZ=America/New_York
    volumes:
      - /home/nextcloud_config:/config
      - /home/nextcloud_data:/data
    depends_on:
      - postgresql
    restart: always
```
