### ISSUE TITLE
[BUG] Warning Memcache after upgrading to 27.0.0

### ISSUE THREAD

**Issue by Intenos** [linuxserver/docker-nextcloud#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading to 27.0.0, I get the warning that no Memcache is installed:

![image](https://github.com/linuxserver/docker-nextcloud/assets/44039580/ff8b57d6-f717-4936-ae70-6d2d5118328b)

I checked that the line
'memcache.local' => '\OC\Memcache\APCu',
is available in the config.php

### Expected Behavior

No warning.

### Steps To Reproduce

Update to 27.0.0 via the updater in Nextcloud and recreate the container by pulling the latest version.

### Environment

```markdown
Open Media Vault

Version
6.4.3-1 (Shaitan)

Prozessor
Intel(R) Pentium(R) CPU J4205 @ 1.50GHz

Kernel
Linux 5.10.0-22-amd64
```

### CPU architecture

x86-64

### Docker creation

```bash
Via Portainer. Not able to insert a screenshot here.
```

### Container logs

```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-package-install to container
[mod-init] Downloading linuxserver/mods:universal-package-install from lscr.io
[mod-init] Installing linuxserver/mods:universal-package-install
[mod-init] linuxserver/mods:universal-package-install applied to container
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

using keys found in /config/keys
**** The following site-confs have extensions other than .conf ****
**** This may be due to user customization. ****
**** You should review the files and rename them to use the .conf extension or remove them. ****
**** nginx.conf will only include site-confs with the .conf extension. ****
/config/nginx/site-confs/default.conf.20230616
**** Adding nodejs to OS package install list ****
**** Adding npm to OS package install list ****
[mod-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/3) Installing c-ares (1.19.1-r0)
(2/3) Installing nodejs (18.16.0-r1)
(3/3) Installing npm (9.6.6-r0)
Executing busybox-1.36.1-r0.trigger
OK: 360 MiB in 259 packages
[custom-init] No custom files found, skipping...
[ls.io-init] done.
[16-Jun-2023 11:37:24] NOTICE: PHP message: PHP Warning:  PHP Startup: Invalid date.timezone value '', using 'UTC' instead in Unknown on line 0
PHP Warning:  PHP Startup: Invalid date.timezone value '', using 'UTC' instead in Unknown on line 0
```

**Comment by j0nnymoe** [comment]
Need your docker creation from portainer, you can copy/paste screenshots.

**Comment by Intenos** [comment]
Do the below screenshots include the information you need?

![image](https://github.com/linuxserver/docker-nextcloud/assets/44039580/30b453d9-a67a-4d46-b0f7-5808122239c1)

![image](https://github.com/linuxserver/docker-nextcloud/assets/44039580/430e3a96-4d88-4d89-af36-505701d26c19)

**Comment by j0nnymoe** [comment]
That's all we need for now, considering v27 is brand new, we'll need to test.

**Comment by Intenos** [comment]
No problem at all. Take your time, it´s not urgent for me. Thanks indeed for the great support!

For me it is already good to know, that for now, I don´t need to try to fix it by myself.

**Comment by ngc7331** [comment]
I think this warning was introduced by https://github.com/nextcloud/server/pull/37766 and it's not a bug.

According to this [documentation](https://docs.nextcloud.com/server/27/admin_manual/configuration_files/files_locking_transactional.html), you also need to configure `memcache.locking` instead of just `memcache.local`

I'm not sure if APCu should be used for filelocking, adding `'memcache.locking' => '\OC\Memcache\APCu',` does solve the warning. And [here](https://help.nextcloud.com/t/memcache-locking-with-apcu/33406) is a related post.

It might be worth installing Redis inside the container or just suggesting that users configure it on their own?

**Comment by Nitrousoxide** [comment]
This looks to be an expectation that the server will have redis as a cache server as part of the infra for the new version of nextcloud.  Implementing that in makes that notice go away.  I would recommend updating the suggested docker compose file to include it, though the config.php needs some additional lines as well.  Here are mine if it's helpful:

```
  'htaccess.RewriteBase' => '/',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' => 
  array (
    'host' => 'redis-nextcloud',
    'port' => 6379,
    'password' => '{password}',
  ),
```

and my compose file
```
---
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /path/to/config:/config
      - /path/to/data:/data
    depends_on:
      - mariadb
    ports:
      - 8080:443
    restart: unless-stopped
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=100
      - MYSQL_ROOT_PASSWORD={sqlrootpass}
      - TZ=America/New_York
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER={sqluser}
      - MYSQL_PASSWORD={sqlpassword}
    volumes:
      - /path/to/mariadb:/config
    restart: unless-stopped
  redis:
    image: redis
    container_name: redis-nextcloud
    restart: always
    command: redis-server --requirepass {redispassword} 
    ports:
      - 6379:6379
```
