### ISSUE TITLE
Caddy proxy keeps redirecting to ip:port

### ISSUE THREAD

**Issue by deanpcmad** [linuxserver/docker-nextcloud#41]
Hey there, thanks for all your work on creating these docker images and for your 2017 media server blog post. I used it and a few of your docker images to set my new server up :smile: 

I've got a bit of an issue with setting Nextcloud up with Caddy server as a proxy.

This is my Caddyfile code:

```
nextcloud.mydomain.com {
  proxy / https://10.0.1.25:8443 {
    insecure_skip_verify
  }
}
```

This is my docker-compose.yml for Nextcloud

```yaml
nextcloud:
  image: linuxserver/nextcloud
  container_name: nextcloud
  volumes:
    - /opt/appdata/nextcloud:/config
    - /opt/appdata/nextcloud-data:/data
  ports:
    - 8443:443
  restart: always
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
```

When I go to access the domain (for this example nextcloud.mydomain.com), it redirects  me to https://10.0.1.25:8443/index.php/login which my browser then complains about an invalid SSL cert. I've tried changing the config.php file in Nextcloud to add my domain in the `trusted_domains` option as well as changing `overwrite.cli.url` to my domain.

Ideally I'd rather the Nextcloud image just listens on 80/8080 and I can just do a normal proxy like I have with all the other docker containers.

Any ideas or is this more an issue with Nextcloud? :smile:
