### ISSUE TITLE
not reachable since some updates

### ISSUE THREAD

**Issue by Homer-Sim** [linuxserver/docker-nextcloud#44]
Hello,
my nextcloud container ran for month without issues. After watchtower update to latest (83) it is tricky.
I am not able to access it. nginx settings unchanged.
I deleted the 83 and went back to 82. After new installation it is accessable but after approx 5-10 minutes it isn't

This is to fin in the container logs before no accessability:
24T18:48:00.687729031Z crond[293]: wakeup dt=60
24T18:48:00.687804496Z crond[293]: file root:
24T18:48:00.687826422Z crond[293]:  line s6-setuidgid abc php7 -f /config/www/nextcloud/cron.php
	

Ubuntu Server 16.04

docker run -it -d \
   --name nextcloud \
   --restart=always \
   -p 82:80 \
   -p 4432:443 \
   -e PUID=33 -e PGID=33 \
   -e TZ=Europe/Berlin \
   -v /docker/config/nextcloud:/config \
   -v /docker/data/nextcloud/:/data \
   linuxserver/nextcloud:82

Any ideas what could be wrong?

**Comment by Homer-Sim** [comment]
Hello,

after a long time of investigation I found the issue.
I dont know why it is like this but it is ...

issue is/was caused by  /conf/nginx/site-conf/default file

this caused (before I added comments) a forwarded address like this https://_/....  instead of https://nextcloud.aurladress.com/.... :
#server {
#  listen 80;
  # server_name _;
  # enforce https
#  return 301 https://$server_name$request_uri;
#}

commenting it and add this to 443 server block helped to solve it:
server {
  listen 80;
  listen 443 ssl;
  server_name _;


Is this a error made by me or a general one?

**Comment by jodumont** [comment]
I have the same issue

**Comment by rosshettel** [comment]
Just chiming in that I attempted an install of nextcloud today and ran into this issue.

**Comment by j0nnymoe** [comment]
@rosshettel information on docker host / how you running the container etc please.

**Comment by rosshettel** [comment]
Running on Ubuntu 16.04, here's the relevant bit of my docker-compose:
```
      nextcloud:
        image: linuxserver/nextcloud
        container_name: nextcloud
        restart: unless-stopped
        environment:
            - PUID=123
            - PGID=123
        volumes:
            - /srv/nextcloud/config:/config
            - /mnt/documents:/data
        ports:
            - '127.0.0.1:8382:80'
```

And then I use nginx on the host to reverse proxy to that port like so:
```
upstream nextcloud {
    server 127.0.0.1:8382;
}

server {
    listen 443 ssl;
    server_name nextcloud.privatedomain;

    access_log /var/log/nginx/access.log access;
    error_log /var/log/nginx/nextcloud-error.log debug;

    include ssl/ssl.conf;

    location / {
        include proxy_config/proxy-control.conf;

        proxy_set_header        Host            $http_host;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Scheme        $scheme;
        proxy_pass http://nextcloud;
    }
}
```

So I think the issue is like @Homer-Sim pointed out, the server block for just HTTP traffic forces a redirect to HTTPS, but because the servername is `_` and that doesn't exist in my nginx proxy configuration it can't find it. FWIW, I haven't had this issue with any of your other containers, not sure if they redirect HTTP traffic by default.

**Comment by homerr** [comment]
Are you both accessing this directly, or behind reverse proxy?

**Comment by danofun** [comment]
I too am having this issue. I'm running Nextcloud behind Traefik. `https://nextcloud.example.com/index.php/login` works properly but `https://nextcloud.example.com` redirects to `https://_`
Let me know how I can help troubleshoot. Here is the Nextcloud section of my `docker-compose.yml`
```
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: always
    volumes:
      - /mnt/user/appdata/nextcloud/:/config
      - /mnt/user/nextcloud/:/data
    environment:
      - PUID=100
      - PGID=99
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:nextcloud.example.com"
      - "traefik.port=443"
      - "traefik.protocol=https"
```
and `/conf/nginx/site-conf/default`
```
upstream php-handler {
  server 127.0.0.1:9000;
# server unix:/var/run/php/php7.0-fpm.sock;
}

server {
  listen 80;
  server_name _;
  # enforce https
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl;
  server_name _;

  ssl_certificate /config/keys/cert.crt;
  ssl_certificate_key /config/keys/cert.key;

  # Add headers to serve security related headers
  add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
  add_header X-Content-Type-Options nosniff;
  # add_header X-Frame-Options "SAMEORIGIN";
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Robots-Tag none;
  add_header X-Download-Options noopen;
  add_header X-Permitted-Cross-Domain-Policies none;
  add_header Referrer-Policy no-referrer;

  # Path to the root of your installation
  root /config/www/nextcloud/;
  # set max upload size
  client_max_body_size 10G;
  fastcgi_buffers 64 4K;

  # Disable gzip to avoid the removal of the ETag header
  gzip off;

  # Uncomment if your server is build with the ngx_pagespeed module
  # This module is currently not supported.
  #pagespeed off;

  index index.php;
  error_page 403 /core/templates/403.php;
  error_page 404 /core/templates/404.php;

  rewrite ^/.well-known/carddav /remote.php/dav/ permanent;
  rewrite ^/.well-known/caldav /remote.php/dav/ permanent;

  # The following 2 rules are only needed for the user_webfinger app.
  # Uncomment it if you're planning to use this app.
  #rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
  #rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

  location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
  }

  location ~ ^/(build|tests|config|lib|3rdparty|templates|data)/ {
    deny all;
  }

  location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
    deny all;
  }

  location / {

    rewrite ^/remote/(.*) /remote.php last;

    rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;

    try_files $uri $uri/ =404;
  }

  location ~ \.php(?:$|/) {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param HTTPS on;
    fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
    fastcgi_pass php-handler;
    fastcgi_intercept_errors on;
  }

  # Adding the cache control header for js and css files
  # Make sure it is BELOW the location ~ \.php(?:$|/) { block
  location ~* \.(?:css|js)$ {
    add_header Cache-Control "public, max-age=7200";
    # Add headers to serve security related headers
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;
    # Optional: Don't log access to assets
    access_log off;
  }

  # Optional: Don't log access to other assets
  location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|swf)$ {
    access_log off;
  }
}
```
