### ISSUE TITLE
[BUG] Setting the PQ database environment variable does not take effect

### ISSUE THREAD

**Issue by harveyff** [linuxserver/docker-nextcloud#503]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hi guys, thanks for your great work.

I am deploying nextcloud on k8s. I followed the official example and specified
```
POSTGRES_HOST
POSTGRES_USER
POSTGRES_DB
POSTGRES_PASSWORD
```
as environment variables, but it does not seem to take effect. It seems that the default is SQLite database when initialized. Does it not support these environment variables?

### Expected Behavior

I expect to use the external PQ database I specify by default when initializing

### Steps To Reproduce

```
   env:
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.databases.nextcloud }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.username }}"
            - name: POSTGRES_HOST
              value: "{{ .Values.postgres.host }}"
```

### Environment

```markdown
- OS:Ubuntu 22.04
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
env:
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.databases.nextcloud }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.username }}"
            - name: POSTGRES_HOST
              value: "{{ .Values.postgres.host }}"
```

### Container logs

```bash
Environment variables are not effective
```
